# Generated by Django 5.2.4 on 2025-12-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_program_rating_avg'),
        ('reviews', '0004_switch_program_to_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.center'),
        ),
    ]
