# Generated by Django 5.2.9 on 2025-12-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_rating_avg_alter_review_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating_avg',
        ),
    ]
