# Generated by Django 5.2.9 on 2025-12-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='program',
            name='price_min',
        ),
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
