# Generated by Django 5.2.4 on 2025-12-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_program_price_max_remove_program_price_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='rating_avg',
        ),
    ]
