# Generated by Django 5.2.9 on 2025-12-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_program_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
